prose:
  rooturl: 'monter_competences'
  media: 'media'
  metadata:
    astuces_stages_creatifs:
      - name: "title"
        field:
          element: "text"
          label: "Titre de la fiche"
          value: "Contribution multiBàO"
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          help: "en une courte phrase"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Mots clés (max 5)"
          placeholder: "choisir des tags"
          options:
            - name: "Ice breaker"
              value: "Ice breaker"
            - name: "Energizer"
              value: "Energizer"
            - name: "Organisation"
              value: "Organisation"
            - name: "Collaboration"
              value: "Collaboration"
            - name: "Citoyenneté"
              value: "Citoyenneté"
