prose:
  media: 'media'
  metadata:
    - name: "title"
      field:
        element: "text"
        label: "Titre"
        value: "Editer ici le titre de votre fiche"
    - name: "description"
      field:
        element: "textarea"
        label: "Description"
        value: ""
    - name: "caption"
      field:
        element: "textarea"
        label: "Lien hypertexte vers l'image de présentation"
        value: ""

